# Generated by Django 2.1.7 on 2019-07-29 04:19

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=255)),
                ('penerbit', models.CharField(max_length=255)),
                ('tanggal_terbit', models.DateField()),
                ('review', common.fields.BinaryTextField()),
                ('in_stock', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'buku',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nama_kategori', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kategori',
            },
        ),
        migrations.AddField(
            model_name='buku',
            name='kategori',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='books.Kategori'),
        ),
    ]
