# Generated by Django 2.1.7 on 2019-07-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='back',
            field=models.ImageField(default='exit', upload_to='bookImage/back/%Y/%d/%D/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buku',
            name='cover',
            field=models.ImageField(default='null', upload_to='bookImage/cover/%Y/%d/%D/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buku',
            name='thumbnail',
            field=models.ImageField(default='exit', upload_to='bookImage/thumbnail/%Y/%d/%D/'),
            preserve_default=False,
        ),
    ]
