# Generated by Django 2.1.7 on 2019-07-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190730_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='back',
            field=models.ImageField(default=None, null=True, upload_to='bookImage/back/%Y/%d/%D/'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='cover',
            field=models.ImageField(default=None, null=True, upload_to='bookImage/cover/%Y/%d/%D/'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='bookImage/thumbnail/%Y/%d/%D/'),
        ),
    ]
