# Generated by Django 2.1.7 on 2019-09-07 10:31

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190907_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='article/thumbnail/%Y/%m/%D/')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='article/image/%Y/%m/%D/')),
                ('judul', models.CharField(default=None, max_length=255, null=True)),
                ('kata_kunci', models.CharField(default=None, max_length=255, null=True)),
                ('deskripsi_pendek', models.CharField(default=None, max_length=255, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, default=0, max_digits=22, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=16, default=0, max_digits=22, null=True)),
                ('isi_berita', common.fields.BinaryTextField()),
            ],
            options={
                'db_table': 'affiliate',
            },
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
