# Generated by Django 2.1.7 on 2019-09-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190907_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='isi_berita',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='isi_berita',
            new_name='isi_artikel',
        ),
    ]
