# Generated by Django 2.1.7 on 2019-09-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190907_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='judul',
            new_name='nama_toko',
        ),
    ]
